server:
  name: "apis"
  address: ":8999"
  workId: 1
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  rateLimit: 50

logger:
  level: "info"
  stdout: true
  rotateExpire: "1d"
  path: "./"

database:
  sync_chain:
    - link: "pgsql:postgres:123456@tcp(localhost:5432)/sync_chain"
  riskcontrol:
    - link: "mysql:riskcontrol:123456@tcp(localhost:3306)/riskcontrol"
  enhanced_riskctrl:
    - link: "pgsql:postgres:123456@tcp(127.0.0.1:5432)/enhanced_riskctrl"
      role: "master"
    - link: "pgsql:postgres:123456@tcp(127.0.0.1:5432)/enhanced_riskctrl"
      role: "slave"
  sync_nft_holding:
    - link: "pgsql:postgres:123456@tcp(127.0.0.1:5432)/sync_nft_holding"
cache:
  duration: 2000

nrpc:
  natsUrl: "127.0.0.1:4222"

# redis
redis:
  default:
    address: 127.0.0.1:10060
    db: 1
  cache:
    address: 127.0.0.1:10060
    db: 2
  aggTx:
    address: 127.0.0.1:6379
    db: 11
