// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cmcqutoe

import (
	"apis/api/cmcqutoe"
)

type ControllerV1 struct{}

func NewV1() cmcqutoe.ICmcqutoeV1 {
	return &ControllerV1{}
}
