// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package enhanced

import (
	"apis/api/enhanced"
	"apis/internal/conf"
	"math/big"

	"github.com/gogf/gf/v2/database/gredis"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gctx"
	"github.com/mpcsdk/mpcCommon/mpcdao"
)

var bigZero = big.NewInt(0)

type ControllerV1 struct {
	redis *gredis.Redis
	// contracts       map[string]*entity.RiskadminContractabi
	// collectionNames map[string][]*entity.RiskadminContractabi
	//db
	enhanced_riskctrl *mpcdao.EnhancedRiskCtrl
	nftHolding        *mpcdao.NftHolding
}

//	func (s *ControllerV1) isEnableChain(chainId int64) bool {
//		if chainId == 0 {
//			return true
//		}
//		chains := service.RiskAdmin().RiskAdminCfg().GetChain(req.ChainId)
//		if chains == nil || chains.IsEnable == 0 {
//			g.Log().Warning(ctx, "chainId not enable:", req)
//			return nil, nil
//		}
//		return false
//	}
//
//	func (s *ControllerV1) getContract(chainId int64, contract string) *entity.RiskadminContractabi {
//		enableContracts := service.RiskAdmin().RiskAdminCfg().AllContract()
//		if chainId > 0 {
//			if contract, ok := enableContracts[mpcdaoutil.RiskadminContractabiKey(chainId, contract)]; ok {
//				return contract
//			}
//			return nil
//		} else {
//			for _, c := range enableContracts {
//				if c.ContractAddress == contract {
//					return c
//				}
//			}
//			return nil
//		}
//	}
//
//	func (s *ControllerV1) isEnableContract(chainId int64, contract string) bool {
//		if chainId == 0 {
//			return true
//		}
//		c := service.RiskAdmin().RiskAdminCfg().GetContract(chainId, contract)
//		if c == nil {
//			return false
//		}
//		return true
//	}
func NewV1() enhanced.IEnhancedV1 {
	///
	ctx := gctx.GetInitCtx()
	r := g.Redis("aggTx")
	_, err := r.Conn(ctx)
	if err != nil {
		panic(err)
	}
	/////

	s := &ControllerV1{
		// contracts:       make(map[string]*entity.RiskadminContractabi),
		// collectionNames: map[string][]*entity.RiskadminContractabi{},
	}
	///

	// contracts := service.RiskAdmin().RiskAdminCfg().AllContract()
	// for _, c := range contracts {
	// 	s.contracts[c.ContractAddress] = c
	// 	if _, ok := s.collectionNames[c.ContractName]; ok {
	// 		s.collectionNames[c.ContractName] = append(s.collectionNames[c.ContractName], c)
	// 	} else {
	// 		s.collectionNames[c.ContractName] = []*entity.RiskadminContractabi{c}
	// 	}
	// }
	// g.Dump(s.contracts)

	s.enhanced_riskctrl = mpcdao.NewEnhancedRiskCtrl(r, conf.Config.Cache.Duration)
	s.nftHolding = mpcdao.NewNftHolding()
	s.redis = r

	return s
}
